org: gabriellopes
service: filebox-api

useDotenv: true

provider:
  name: aws
  runtime: nodejs24.x
  timeout: 30
  architecture: arm64
  environment:
    BUCKET_NAME: ${env:BUCKET_NAME}
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
            - dynamodb:BatchGetItem
          Resource:
            - !GetAtt FilesTable.Arn
        - Effect: Allow
          Action:
            - s3:*
          Resource:
            - arn:aws:s3:::${env:BUCKET_NAME}/*

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

build:
  esbuild:
    minify: true
    sourcemap: false

package:
  individually: true

functions:
  get-download-url:
    handler: src/functions/http/get-download-url.handler
    events:
      - httpApi:
          path: /download
          method: POST
  get-upload-url:
    handler: src/functions/http/get-upload-url.handler
    events:
      - httpApi:
          path: /upload
          method: POST
  list-files:
    handler: src/functions/http/list-files.handler
    events:
      - httpApi:
          path: /files
          method: GET
  delete-files:
    handler: src/functions/http/delete-files.handler
    events:
      - httpApi:
          path: /files/delete
          method: POST
  copy-files:
    handler: src/functions/http/copy-files.handler
    events:
      - httpApi:
          path: /files/copy
          method: POST
  restore-files:
    handler: src/functions/http/restore-files.handler
    events:
      - httpApi:
          path: /files/restore
          method: POST
  rename-file:
    handler: src/functions/http/rename-file.handler
    events:
      - httpApi:
          path: /files/{id}/rename
          method: POST
  complete-upload:
    handler: src/functions/s3/complete-upload.handler
    events:
      - s3:
          existing: true
          bucket: ${env:BUCKET_NAME}
          event: s3:ObjectCreated:*
  complete-file-deletion:
    handler: src/functions/s3/complete-file-deletion.handler
    events:
      - s3:
          existing: true
          bucket: ${env:BUCKET_NAME}
          event: s3:ObjectRemoved:DeleteMarkerCreated
  cleanup-file-deletion:
    handler: src/functions/s3/cleanup-file-deletion.handler
    events:
      - s3:
          existing: true
          bucket: ${env:BUCKET_NAME}
          event: s3:ObjectRemoved:Delete

resources:
  Resources:
    FilesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: FileboxFiles

        BillingMode: PAY_PER_REQUEST

        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S

        KeySchema:
          - AttributeName: id
            KeyType: HASH

        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

        # AttributeDefinitions:
        #   - AttributeName: pk
        #     AttributeType: S
        #   - AttributeName: sk
        #     AttributeType: S
        #   - AttributeName: gsi1pk
        #     AttributeType: S
        #   - AttributeName: gsi1sk
        #     AttributeType: S

        # KeySchema:
        #   - AttributeName: pk
        #     KeyType: HASH
        #   - AttributeName: sk
        #     KeyType: RANGE

        # GlobalSecondaryIndexes:
        #   - IndexName: GSI1-Checksum
        #     KeySchema:
        #       - AttributeName: gsi1pk
        #         KeyType: HASH
        #       - AttributeName: gsi1sk
        #         KeyType: RANGE
        #     Projection:
        #       ProjectionType: ALL

        # SSESpecification:
        #   SSEEnabled: true
